language: elixir
elixir: 1.6.3
otp_release: 20.2

before_script:
  - MIX_ENV=test mix compile --warnings-as-errors
  - travis_wait mix dialyzer --plt
script:
  - mix dialyzer --halt-exit-status
  - mix test

sudo: required
dist: trusty
cache:
  directories:
    - _build
    - deps
